In [0]:
doc1 = "I am coming home"
doc2 = "Who is home?"
doc3 = "The gods are not to blame"
doc4 = "I am confident about his abilities"
x = [doc1, doc2, doc3, doc4]



In [27]:
import itertools
import numpy
from deeppavlov.models.tokenizers.spacy_tokenizer import StreamSpacyTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer

from collections import Counter

# create tokenizer
# Whats the effect toggling lemma value?
tokenizer = StreamSpacyTokenizer(lemmas=False)
x_tokenized = tokenizer(x)
print (x_tokenized)

# Get all of the unique entries you have
varnames = tuple(sorted(set(itertools.chain(*x_tokenized))))

# Get a list of all of the combinations you have
expanded = [tuple(itertools.combinations(d, 2)) for d in x_tokenized]
expanded = itertools.chain(*expanded)

# Sort the combinations so that A,B and B,A are treated the same
expanded = [tuple(sorted(d)) for d in expanded]

# count the combinations
c = Counter(expanded)

# Create the table
table = numpy.zeros((len(varnames),len(varnames)), dtype=int)

for i, v1 in enumerate(varnames):
    for j, v2 in enumerate(varnames[i:]):        
        j = j + i 
        table[i, j] = c[v1, v2]
        table[j, i] = c[v1, v2]

# Display the output
for row in table:
    print(row)
table.shape

[['i', 'am', 'coming', 'home'], ['who', 'is', 'home'], ['the', 'gods', 'are', 'not', 'to', 'blame'], ['i', 'am', 'confident', 'about', 'his', 'abilities']]
[0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0]
[1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0]
[1 1 0 0 0 1 1 0 1 1 2 0 0 0 0 0]
[0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0]
[0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0]
[0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
[1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0]
[0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0]
[1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0]
[0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1]
[1 1 2 0 0 1 1 0 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
[0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0]
[0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0]
[0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]


(16, 16)

In [0]:
varnames

('ability',
 'about',
 'be',
 'blame',
 'come',
 'confident',
 'god',
 'home',
 'not',
 'the',
 'to',
 'who')